version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: fundraiser-db
    restart: always
    ports:
      - 3356:3306
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: fundraiser-php
    restart: always
    ports:
      - 80:80
  